### ISSUE TITLE
issues using the tutorial4_regularization_PoissonGLM

### ISSUE THREAD

**Issue by chongtianyifa** [pillowlab/GLMspiketraintutorial#4]
Hi,

Thank you for the easily implemented code. I have two questions about the Matlab version of ridge regularization of Poisson GLM. 
1. How to reconstruct the response (y) once we got the w_ridge? I tried y_prediction = glmval(w_ridge, X_training, 'log', 'Constant','off'). However, the reconstruction is very different from the actual spike train.
2.  How is this ridge regularization different from the matlab function [B, FitInfo] = lassoglm(Xtrain,spstrain,'poisson','Alpha',0.01,'NumLambda', 20)? The problem is that the Matlab function lassoglm runs very slowly.

Thank you,
Chris

**Comment by jpillow** [comment]
Thanks for your comment and questions!  Here are some quick replies:

1.  If you look in tutorial 1 (Section 9) there is a block of code for simulating the response of the fitted GLM.  This would give you either the predicted spike train (or samples of the model's response to the same stimulus).  
2. I'm not familiar with the 'lassoglm' function, but I would assume this is performing L1 regularization (ie. includes a penalty on the sum of absolute values of the coefficients) instead of ridge (aka "L2") regularization, which is a penalty on the sum-of-squares of the coefficients.  Lasso is in general harder to solve because the penalty function is non-differentiable at 0, so you need special techniques.  (There is a whole literature on methods for lasso, so there may be faster algorithms than the one built into lassoglm, but in general I would not be surprised if L1 regularization runs more slowly than L2 / ridge). 

Best wishes,
Jonathan

**Comment by chongtianyifa** [comment]
Hi Jonathan,

Thank you for the quick response. I will try to use the code in tutoral 1. In my experiment, I want to explore the relationship between neural spiking activity and different timescales of certain stimuli and actions (generated by sets of basis function). Is ridge regularization better than Lasso as all predictors regarding the same stimuli might be important although they are highly correlated (Lasso regularization might only keep one)? Can you give me some advice?

Thanks,
Chris
